### ISSUE TITLE
How does the client fit into a supervision tree

### ISSUE THREAD

**Issue by thinktainer** [sanmiguel/websocket_client#41]
Apologies if the answer to this question is obvious to you, or if you'd prefer questions like this to be asked elsewhere, I did a best effort of trying to find the answer by myself, or find a more suitable place to ask it. 

My use case is this:
I would like to use this library for bi-directional communication as a chat bot.

The problem I have is:
I can't figure out how to properly implement the the behaviour so that it is started in a supervision tree and the name of my implementation is registered in the start_link function, as it is provided by the various gen_* behaviours by otp. The reason i want to do this, is that I can send messages to the web socket by using a name for the websocket_client implementation, rather than having to remember the pid.

I have gone for the naive solution of calling erlang:register() in the start_link function, and erlang:unregister() in the websocket_terminate callback. Do you see any problem with this solution? Do you think it would be preferable to use proc:spawn_link() for this?

I'm a little confused, as under the hood you use gen_fsm, but it is obvious why that wouldn't be registered via it's name, as then there could only ever be one websocket_client in the system, if it was registered via it's name.

How would you advise using the client in an otp application?

**Comment by thinktainer** [comment]
Ok, I think I figured this out now.
I should implement my use case of having a message sender by exposing API functions like `send(Message)` and forwarding that call to `self() ! Message`, then picking it up in `handle_info()` and using `{reply, Message, State}` in there. I'm happy to close this, if you think that is correct?

**Comment by sanmiguel** [comment]
I'm so sorry I didn't get back to you before. Github didn't notify me about the issue being created.

You raise an interesting point about process registration - this isn't a use case I'd covered before but definitely something that would be great to have.

Perhaps it would be possible to extend the `start_link/3,4` functions to include the ability to include the registered name and pass it through to `gen_fsm:start_link/4` where necessary.

Conventionally with e.g. `gen_server`, one does something such as:

``` erlang
start_link() ->
    gen_server:start_link({local, ?MODULE}, ?MODULE, [], []).

send(Foo) ->
   gen_server:call(?MODULE, {send, Foo}).

handle_call({send, Foo}, ...) -> ...
```

If I add an additional `websocket_client:start_link/5` definition that takes a process name and passes it to `gen_fsm:start_link/4` then you'd be able to register and use a `websocket_client` process exactly as with `gen_fsm`, `gen_server` etc.

In respect to your solution: register on `start_link` and unregister on `websocket_terminate` sounds viable until I can implement it natively.

**Comment by thinktainer** [comment]
Awesome, Thank You for getting back to me. I'm happy for you to close this, or use it to track, however you see fit. Thank You for taking the time to assess the feasibility of my solution too.

**Comment by unrealhoang** [comment]
@thinktainer @sanmiguel How do you guys know when the client is ready to send message (i.e the fsm in `connected` state)? I'm having the problem that when I make the client send a message to the server (using `websocket_client:cast(__MODULE__, {text, <<"message">>})`) from another process too soon, the client just drop that message and never send to the server.
My solution would be let the client's supervisor know when the client is ready, and then notify the consumer process to begin subscribe/sending message. Is that appropriate?

**Comment by sanmiguel** [comment]
Hi @unrealhoang - you can use the `onconnect/2` callback to perform an action when the websocket connection is up and running. The `ws_client` in the test suites does exactly this.
`ws_client:start_link/0-2` sends `self()` in the init args, then later, in `onconnect/2`, the client sends a message to the process that started it. When you receive that message, you know the client is connected.
Relevant links:
https://github.com/sanmiguel/websocket_client/blob/master/test/ws_client.erl#L91
https://github.com/sanmiguel/websocket_client/blob/master/test/wc_SUITE.erl#L67-L68

**Comment by unrealhoang** [comment]
Great @sanmiguel, thanks for you kind response :)

**Comment by sanmiguel** [comment]
@unrealhoang - it's possibly noteworthy that `onconnect/2` will be called every time the connection is established. If you set it up to auto-reconnect (by returning `{reconnect, State}` from your `init/1` callback), your `onconnect/2` handler may be called multiple times if the connection is unreliable.

**Comment by pikeas** [comment]
Would love to see proper process registration (local/global/via)!

**Comment by sanmiguel** [comment]
@thinktainer @pikeas it's been a long time coming, but I finally merged a PR today (H/T @rroupski) that adds the possibility for process registration via `websocket_client:start_link/5`

This has been tagged (along with a couple of minor admin changes to update the Travis-CI setup, and remove the local `rebar3` executable) as `1.2.1`, and published to hex.pm.

I'll close this issue now, but *please* feel free to reopen if there's more you were after.

**Comment by pikeas** [comment]
Here's the PR for reference: https://github.com/sanmiguel/websocket_client/pull/46

Looks great, I'll kick the tires soon. Might be worth updating docs/example?
